language: python
python:
  - 3.8.6
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - pipenv run flake8
  - pipenv run pytest --cov=victorbaptistalemos_libpythonpro
after_success:
  - codecov